const ADD_AFFILIATE_DETAILS='ADD_AFFILIATE_DETAILS';
const EDIT_AFFILIATE_DETAILS = 'EDIT_AFFILIATE_DETAILS';
const DELETE_AFFILIATE_DETAILS = 'DELETE_AFFILIATE_DETAILS';

export {
    ADD_AFFILIATE_DETAILS,
    EDIT_AFFILIATE_DETAILS,
    DELETE_AFFILIATE_DETAILS,
};