const ADD_ROLES_DETAILS='ADD_ROLES_DETAILS';
const EDIT_ROLES_DETAILS = 'EDIT_ROLES_DETAILS';
const DELETE_ROLES_DETAILS = 'DELETE_ROLES_DETAILS';

export {
    ADD_ROLES_DETAILS,
    EDIT_ROLES_DETAILS,
    DELETE_ROLES_DETAILS,
};